package com.DTMK.Online.Bookkeeping.Website.Project.mapper;

import com.DTMK.Online.Bookkeeping.Website.Project.entity.ExchangeRate;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

/**
 * MyBatis mapper for the {@code exchange_rate} table.
 * <p>
 * The table is write-mostly: it is populated exclusively by
 * {@link com.DTMK.Online.Bookkeeping.Website.Project.config.CurrencyScheduler}
 * once a day. The single-row read ({@link #findByCurrencyCode}) is
 * used by the service layer to decide insert-vs-update for each
 * supported currency; {@link #findAll} powers the
 * {@code GET /api/exchange-rates} endpoint that the frontend uses to
 * populate its currency-conversion dropdown.
 * <p>
 * column / property mapping is handled by MyBatis' default
 * map-underscore-to-camel-case (enabled in application.yml), so
 * {@code currency_code} binds to {@code currencyCode} and
 * {@code last_updated} binds to {@code lastUpdated} automatically.
 */
@Mapper
public interface ExchangeRateMapper {

    /**
     * Read every row in the table, ordered alphabetically by code so
     * the frontend dropdown is deterministic. The table is tiny
     * (~15 rows) so there is no need to page or filter.
     */
    @Select("SELECT * FROM exchange_rate ORDER BY currency_code ASC")
    List<ExchangeRate> findAll();

    /**
     * Lookup by ISO 4217 code. Returns {@code null} when the row does
     * not exist yet — the caller uses that to decide between
     * {@link #insert(ExchangeRate)} and {@link #update(ExchangeRate)}.
     */
    @Select("SELECT * FROM exchange_rate WHERE currency_code = #{code}")
    ExchangeRate findByCurrencyCode(@Param("code") String code);

    /**
     * Insert a brand-new row. {@code id} is auto-generated by the DB
     * and is not bound from the POJO. The service layer is expected
     * to have already stamped {@code lastUpdated}.
     */
    @Insert("INSERT INTO exchange_rate(currency_code, rate, last_updated) " +
            "VALUES(#{currencyCode}, #{rate}, #{lastUpdated})")
    int insert(ExchangeRate rate);

    /**
     * Update the rate and timestamp of an existing row, matched on
     * {@code currency_code}. The {@code id} on the POJO is ignored —
     * the natural key (currency_code) is what identifies the row.
     */
    @Update("UPDATE exchange_rate " +
            "SET rate = #{rate}, last_updated = #{lastUpdated} " +
            "WHERE currency_code = #{currencyCode}")
    int update(ExchangeRate rate);
}
